export type Faction = 'Alliance' | 'Horde'
export type Slot =
  | 'head'
  | 'neck'
  | 'shoulder'
  | 'back'
  | 'chest'
  | 'shirt'
  | 'tabard'
  | 'wrist'
  | 'hands'
  | 'waist'
  | 'legs'
  | 'feet'
  | 'finger_1'
  | 'finger_2'
  | 'trinket_1'
  | 'trinket_2'
  | 'main_hand'
  | 'off_hand'
  | 'ranged'
